# Generated by Django 2.1.2 on 2018-10-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
                ('books_int', models.IntegerField(default=0)),
                ('books_read', models.TextField(null=True)),
            ],
        ),
    ]
