# Generated by Django 2.1.2 on 2018-11-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinglog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('books_int', models.IntegerField(default=0)),
                ('books_read', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
