# Generated by Django 2.1.2 on 2018-11-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readinglog', '0002_auto_20181106_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbooks',
            name='books_int',
        ),
    ]
